build:
  maxIssues: 0 # break the build if more than ten weighted issues are found
  weights:
    complexity: 1 # every rule of the complexity rule set should count as if two issues were found...

output-reports:
  active: true
  exclude:
    #  - 'HtmlOutputReport'
    - 'TxtOutputReport'
    - 'XmlOutputReport'
    - 'SarifOutputReport'
